### ISSUE TITLE
When I change with values in the config.json and the .txt files in the sample fold it doesnt do anything.

### ISSUE THREAD

**Issue by kdaly93** [Kthateyo/Instagram-PyBot#1]
This might be a "me" problem but it seems like upon saving the updated values, vscode doesn't register these changes.

**Comment by kestivvi** [comment]
Make sure that you are making changes to the right files. While you're starting the bot by `python main.py start <dirpath>`, the files you want to update are in this dirpath. So if you update files in sample folder you gonna run `python main.py start sample`

**Comment by kestivvi** [comment]
As it was an inactive thread for some time and from this time there were a couple of updates to the bot, I going to close this thread as unnecessary.
